// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStqb0Ml7cHVswXnvBHPBzMlEDsz1gaRk',
    appId: '1:911490191396:web:d940e0f80909862dee08b1',
    messagingSenderId: '911490191396',
    projectId: 'flutterclone-e7a51',
    authDomain: 'flutterclone-e7a51.firebaseapp.com',
    storageBucket: 'flutterclone-e7a51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMlzLlmvwGFZcosW9ifsry3Euym-jSO30',
    appId: '1:911490191396:android:5a8b5afd8840dc12ee08b1',
    messagingSenderId: '911490191396',
    projectId: 'flutterclone-e7a51',
    storageBucket: 'flutterclone-e7a51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOdNSEuWE2Fm7hif9vPIbmu04PXnZcGeU',
    appId: '1:911490191396:ios:96569c46f22fe88dee08b1',
    messagingSenderId: '911490191396',
    projectId: 'flutterclone-e7a51',
    storageBucket: 'flutterclone-e7a51.appspot.com',
    iosBundleId: 'com.example.newyoutube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOdNSEuWE2Fm7hif9vPIbmu04PXnZcGeU',
    appId: '1:911490191396:ios:96569c46f22fe88dee08b1',
    messagingSenderId: '911490191396',
    projectId: 'flutterclone-e7a51',
    storageBucket: 'flutterclone-e7a51.appspot.com',
    iosBundleId: 'com.example.newyoutube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStqb0Ml7cHVswXnvBHPBzMlEDsz1gaRk',
    appId: '1:911490191396:web:65fca736156ea254ee08b1',
    messagingSenderId: '911490191396',
    projectId: 'flutterclone-e7a51',
    authDomain: 'flutterclone-e7a51.firebaseapp.com',
    storageBucket: 'flutterclone-e7a51.appspot.com',
  );
}
